// This file is auto-generated by scripts/generate-page-docs.mjs
// Do not edit by hand.

import doc0 from "@/content/page-docs/about.json";
import doc1 from "@/content/page-docs/admissions.json";
import doc2 from "@/content/page-docs/apply.json";
import doc3 from "@/content/page-docs/careers.json";
import doc4 from "@/content/page-docs/donations.json";
import doc5 from "@/content/page-docs/government-employees.json";
import doc6 from "@/content/page-docs/home.json";
import doc7 from "@/content/page-docs/portal-dashboard.json";
import doc8 from "@/content/page-docs/portal.json";
import doc9 from "@/content/page-docs/program-id.json";
import doc10 from "@/content/page-docs/program.json";
import doc11 from "@/content/page-docs/request-info.json";
import doc12 from "@/content/page-docs/reset-password.json";
import doc13 from "@/content/page-docs/student-experience.json";
import doc14 from "@/content/page-docs/tuition.json";

export const pageDocSlugs = [
  "about",
  "admissions",
  "apply",
  "careers",
  "donations",
  "government-employees",
  "home",
  "portal-dashboard",
  "portal",
  "program-id",
  "program",
  "request-info",
  "reset-password",
  "student-experience",
  "tuition"
] as const;

export type PageDocSlug = (typeof pageDocSlugs)[number];

const PAGE_DOCS: Record<string, unknown> = {
  "about": doc0,
  "admissions": doc1,
  "apply": doc2,
  "careers": doc3,
  "donations": doc4,
  "government-employees": doc5,
  "home": doc6,
  "portal-dashboard": doc7,
  "portal": doc8,
  "program-id": doc9,
  "program": doc10,
  "request-info": doc11,
  "reset-password": doc12,
  "student-experience": doc13,
  "tuition": doc14,
};

export function getPageDoc(slug: string): unknown | null {
  return PAGE_DOCS[slug] ?? null;
}
